spring.application.name=TravelManagement


spring.datasource.url=jdbc:mysql://localhost:3306/TravelManagement
spring.datasource.username=root
spring.datasource.password=Saisree@09
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.name=admin
spring.security.user.password=Admin@123








spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bmwtravelmanagement@gmail.com
spring.mail.password=cyan dvfw rfoe kups



spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


razorpay.key.id=rzp_test_T5OB2v802dYJ8x
razorpay.key.secret=rmyH5OC3YAkcWnElj6MJYJ9c


cloudinary.cloud-name=dxplahu2b
cloudinary.api-key=914412859728388
cloudinary.api-secret=mwj9m7xZPb5uhqiAhk1zSX880jw